remote_theme: jekyll/minima
title: Tiny-Learning-Based-MPC Project Page
description:

repository: robora-lab/Tiny-Learning-Based-MPC

navigation:
  - title: Robora Lab
    url: https://roboralab.com/index.html
  - title: GitHub
    url: https://github.com/Robora-Lab
