title: UAV-USV Landing
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/uav-usv-landing" # the subpath of your site, e.g. /blog
url: "http://robora-lab.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Robora Lab # add your name
author-img: robora.png # add your photo
about-author: Description # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address


# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
